<template>
	<div id="app">
		<section class="hero is-medium is-info is-bold">
			<div class="hero-body">
				<div class="container">
					<h1 class="title">vue-scrolling-table</h1>
					<h2 class="subtitle">Sample app for the VueScrollingTableComponent</h2>
				</div>
			</div>
		</section>

		<section class="section">
			<div class="container">
				<div class="content">
					<p>
						<b>vue-scrolling-table</b> is a Vue that provides a flexbox-based table control, where the header, body, and footer of the control are rendered via named slots for
						maximum flexibility, and the component allows the body to be scrolled horizontally and vertically as needed.
					</p>

					<p>
						For detailed documentation, please see <a href="https://github.com/richardtallent/vue-scrolling-table">the Github repository</a>. (The repo for this page is also
						<a href="https://github.com/richardtallent/vue-scrolling-table-sample">available on Github</a>.)
					</p>

					<p>
						Note: this demo page uses the Bulma library for basic styling, and that styling overides a few details of the default vue-scrolling-table, notably removing the border
						from the header cells and adding rounded corners.
					</p>

					<h2 class="title is-2 is-spaced">Demo!</h2>

					<div class="box">
						<vue-scrolling-table
							:scroll-horizontal="state.scrollHorizontal"
							:scroll-vertical="state.scrollVertical"
							:sync-header-scroll="state.syncHeaderScroll"
							:sync-footer-scroll="state.syncFooterScroll"
							:include-footer="state.includeFooter"
							:dead-area-color="state.deadAreaColor"
							:class="{ freezeFirstColumn: state.freezeFirstColumn }"
						>
							<template #thead>
								<tr>
									<th v-for="col in useColumns" :class="col.cssClasses" :key="col.id">{{ col.title }}</th>
								</tr>
							</template>
							<template #tbody>
								<tr v-for="item in items" :key="item.id">
									<td v-for="col in useColumns" :class="col.cssClasses" :key="col.id">{{ item[col.id] }}</td>
								</tr>
							</template>
							<template #tfoot>
								<tr>
									<th :colspan="useColumns.length">My footer text</th>
								</tr>
							</template>
						</vue-scrolling-table>
					</div>
					<p>Fake sample data courtesy <a href="https://www.generatedata.com/">generatedata.com</a>.</p>

					<h3>Play with the options!</h3>
					<div class="field">
						<div class="control">
							<label class="checkbox"><input v-model="state.scrollVertical" type="checkbox" /> Vertical scrolling</label>
						</div>
					</div>
					<div class="field">
						<div class="control">
							<label class="checkbox"><input v-model="state.scrollHorizontal" type="checkbox" /> Horizontal scrolling</label>
						</div>
					</div>
					<div class="field">
						<div class="control">
							<label class="checkbox"><input v-model="state.includeFooter" type="checkbox" /> Show footer</label>
						</div>
					</div>
					<div class="field">
						<div class="control">
							<label class="checkbox"><input v-model="state.syncHeaderScroll" type="checkbox" /> Sync horizontal header scrolling with body</label>
						</div>
					</div>
					<div class="field">
						<div class="control">
							<label class="checkbox"><input v-model="state.syncFooterScroll" type="checkbox" /> Sync horizontal footer scrolling with body</label>
						</div>
					</div>
					<div class="field">
						<div class="control">
							<label class="text"><input type="color" v-model="state.deadAreaColor" /> Dead area color</label>
						</div>
					</div>
					<div class="field">
						<div class="control">
							<label class="text"><input type="number" v-model="state.maxRows" min="0" max="100" /> Rows to show (0-100)</label>
						</div>
					</div>
					<div class="field">
						<div class="control">
							<label class="text"><input type="number" v-model="state.maxColumns" min="0" max="11" /> Columns to show (0-11)</label>
						</div>
					</div>
					<div class="field">
						<div class="control">
							<label class="checkbox"><input v-model="state.freezeFirstColumn" type="checkbox" /> Freeze first column (webkit only)</label>
						</div>
					</div>

					<h2 class="title is-2 is-spaced">Contact</h2>

					<p>For more information, please feel free to reach out to me using Github issues.</p>
				</div>
			</div>
		</section>
	</div>
</template>
<script setup lang="ts">
import { computed, reactive } from "vue"
import VueScrollingTable from "./VueScrollingTable.vue"

const state = reactive({
	scrollVertical: true,
	scrollHorizontal: true,
	syncHeaderScroll: true,
	syncFooterScroll: true,
	includeFooter: true,
	deadAreaColor: "#DDDDDD",
	maxRows: 100,
	maxColumns: 11,
	freezeFirstColumn: false,
	columns: [
		{ id: "id", title: "ID", cssClasses: "" },
		{ id: "firstName", title: "First Name", cssClasses: "" },
		{ id: "lastName", title: "Last Name", cssClasses: "" },
		{ id: "companyName", title: "Company Name", cssClasses: "w2" },
		{ id: "address", title: "Address", cssClasses: "w2" },
		{ id: "city", title: "City", cssClasses: "" },
		{ id: "region", title: "Region", cssClasses: "" },
		{ id: "postal", title: "Postal Code", cssClasses: "" },
		{ id: "country", title: "Country", cssClasses: "" },
		{ id: "phone", title: "Phone", cssClasses: "" },
		{ id: "email", title: "Email", cssClasses: "" },
	],
	allItems: [
		{
			id: 1,
			firstName: "Howard",
			lastName: "Ramirez",
			companyName: "Cubilia Curae; Phasellus Industries",
			phone: "1-607-782-6985",
			email: "Ut.nec@eget.com",
			address: "P.O. Box 690, 4766 Massa St.",
			city: "New Plymouth",
			region: "North Island",
			postal: "538527",
			country: "South Sudan",
			latlong: "-65.0162, -52.0815",
		},
		{
			id: 2,
			firstName: "Donna",
			lastName: "Rhodes",
			companyName: "Nunc Mauris Industries",
			phone: "1-184-778-4950",
			email: "porttitor.tellus.non@eratvel.org",
			address: "P.O. Box 359, 1862 Laoreet, Av.",
			city: "Saint-Remy-Geest",
			region: "Waals-Brabant",
			postal: "DL3N 3CV",
			country: "Botswana",
			latlong: "1.57577, -169.19843",
		},
		{
			id: 3,
			firstName: "Wade",
			lastName: "Reynolds",
			companyName: "Duis Risus LLC",
			phone: "454-3889",
			email: "nunc@mauris.com",
			address: "Ap #132-6084 Vitae St.",
			city: "Colombo",
			region: "Paraná",
			postal: "563593",
			country: "Mali",
			latlong: "-2.21279, 172.48945",
		},
		{
			id: 4,
			firstName: "Rae",
			lastName: "Leach",
			companyName: "Aliquet Molestie LLC",
			phone: "370-8602",
			email: "luctus@ligula.co.uk",
			address: "2271 Dolor. Rd.",
			city: "Hamburg",
			region: "HH",
			postal: "07338",
			country: "United States Minor Outlying Islands",
			latlong: "22.18339, -119.56959",
		},
		{
			id: 5,
			firstName: "Oleg",
			lastName: "Miles",
			companyName: "Maecenas Mi PC",
			phone: "491-4122",
			email: "nulla.In@magnaDuis.com",
			address: "2655 Nibh. St.",
			city: "San Rafael",
			region: "Alajuela",
			postal: "22850",
			country: "Finland",
			latlong: "89.32097, 132.01573",
		},
		{
			id: 6,
			firstName: "Thane",
			lastName: "Bright",
			companyName: "Sem Egestas Blandit LLP",
			phone: "1-230-283-4753",
			email: "ante.blandit@pharetra.org",
			address: "8064 Ante St.",
			city: "Purulia",
			region: "Jharkhand",
			postal: "40118",
			country: "Serbia",
			latlong: "-40.57058, -7.18883",
		},
		{
			id: 7,
			firstName: "Hashim",
			lastName: "Salazar",
			companyName: "Mi Tempor Lorem Institute",
			phone: "551-1721",
			email: "quis@Cumsociisnatoque.com",
			address: "5177 Auctor. Avenue",
			city: "Soye",
			region: "Namen",
			postal: "4532",
			country: "Belarus",
			latlong: "17.0762, 80.93834",
		},
		{
			id: 8,
			firstName: "Aspen",
			lastName: "Tanner",
			companyName: "Pharetra Nibh Aliquam Ltd",
			phone: "192-2717",
			email: "Donec.est@etarcuimperdiet.edu",
			address: "Ap #260-6014 Donec Rd.",
			city: "Vienna",
			region: "Wie",
			postal: "2972 ZB",
			country: "South Sudan",
			latlong: "-15.28813, 32.10255",
		},
		{
			id: 9,
			firstName: "Eaton",
			lastName: "Harris",
			companyName: "Suspendisse Commodo Inc.",
			phone: "1-862-415-8875",
			email: "et@natoque.net",
			address: "754-1058 In Ave",
			city: "Belfast",
			region: "U",
			postal: "47351",
			country: "Saint Barthélemy",
			latlong: "-1.12993, 77.69448",
		},
		{
			id: 10,
			firstName: "Scott",
			lastName: "Savage",
			companyName: "Molestie LLP",
			phone: "1-261-128-3939",
			email: "venenatis@erat.co.uk",
			address: "P.O. Box 397, 4261 Iaculis Road",
			city: "Sagamu",
			region: "Ogun",
			postal: "0576",
			country: "Portugal",
			latlong: "10.5385, -71.53813",
		},
		{
			id: 11,
			firstName: "Amethyst",
			lastName: "Moore",
			companyName: "Leo Elementum Incorporated",
			phone: "111-2420",
			email: "egestas.Fusce.aliquet@quamdignissimpharetra.org",
			address: "Ap #615-2475 Sagittis Rd.",
			city: "Tallahassee",
			region: "FL",
			postal: "17070",
			country: "Turks and Caicos Islands",
			latlong: "-64.01867, -170.5388",
		},
		{
			id: 12,
			firstName: "Russell",
			lastName: "Roy",
			companyName: "Class Incorporated",
			phone: "555-5784",
			email: "ac@semper.org",
			address: "4023 Donec Rd.",
			city: "Galway",
			region: "Connacht",
			postal: "91975-667",
			country: "Bahrain",
			latlong: "64.10092, -55.87219",
		},
		{
			id: 13,
			firstName: "Chloe",
			lastName: "Shepard",
			companyName: "Ornare Libero At PC",
			phone: "1-851-813-9116",
			email: "ut.odio.vel@dui.com",
			address: "Ap #655-4944 Velit. Rd.",
			city: "Alacant",
			region: "Comunitat Valenciana",
			postal: "5316",
			country: "Guyana",
			latlong: "-35.97468, 163.65834",
		},
		{
			id: 14,
			firstName: "Zenaida",
			lastName: "Butler",
			companyName: "Quisque Tincidunt Company",
			phone: "202-4795",
			email: "orci.lacus@duisemper.com",
			address: "Ap #857-3500 Fermentum Rd.",
			city: "Cheltenham",
			region: "Gloucestershire",
			postal: "85-623",
			country: "Mali",
			latlong: "-40.12836, -141.78587",
		},
		{
			id: 15,
			firstName: "Akeem",
			lastName: "Houston",
			companyName: "Turpis Vitae Purus LLP",
			phone: "1-719-939-6901",
			email: "euismod.ac@velfaucibus.co.uk",
			address: "Ap #901-4402 Sed Road",
			city: "Sapele",
			region: "Delta",
			postal: "50417",
			country: "France",
			latlong: "-38.76102, -154.03756",
		},
		{
			id: 16,
			firstName: "Alma",
			lastName: "Whitehead",
			companyName: "Maecenas Iaculis Aliquet Inc.",
			phone: "1-457-545-6623",
			email: "arcu.vel.quam@accumsanconvallis.ca",
			address: "5449 Malesuada St.",
			city: "Sokoto",
			region: "Sokoto",
			postal: "44922",
			country: "Hong Kong",
			latlong: "36.81221, -29.96226",
		},
		{
			id: 17,
			firstName: "Prescott",
			lastName: "Willis",
			companyName: "Proin Dolor LLP",
			phone: "1-758-337-8375",
			email: "blandit.enim.consequat@Nunc.org",
			address: "P.O. Box 242, 2810 Ut Ave",
			city: "Toruń",
			region: "Kujawsko-pomorskie",
			postal: "4584",
			country: "Guyana",
			latlong: "29.29962, -31.61446",
		},
		{
			id: 18,
			firstName: "Rooney",
			lastName: "Harrell",
			companyName: "Dui Associates",
			phone: "1-371-619-4460",
			email: "facilisis.vitae.orci@ligula.co.uk",
			address: "4523 Sapien, Rd.",
			city: "Guna",
			region: "Madhya Pradesh",
			postal: "2978",
			country: "Sweden",
			latlong: "23.9795, -59.82102",
		},
		{
			id: 19,
			firstName: "Hu",
			lastName: "Wood",
			companyName: "Mus Proin Institute",
			phone: "376-0930",
			email: "ornare.lectus.ante@atpretiumaliquet.edu",
			address: "1805 Nibh. St.",
			city: "Campagna",
			region: "Campania",
			postal: "14530",
			country: "Mongolia",
			latlong: "-4.75482, 91.77837",
		},
		{
			id: 20,
			firstName: "Beck",
			lastName: "Brennan",
			companyName: "Pede Et Risus LLP",
			phone: "418-9774",
			email: "Morbi.quis.urna@In.ca",
			address: "P.O. Box 324, 5727 Vulputate St.",
			city: "Missoula",
			region: "Montana",
			postal: "24803",
			country: "Nauru",
			latlong: "2.15658, -68.28417",
		},
		{
			id: 21,
			firstName: "Quincy",
			lastName: "Knight",
			companyName: "Eu Corporation",
			phone: "1-222-411-1840",
			email: "ut.nisi@sapien.org",
			address: "P.O. Box 873, 4719 Dictum Rd.",
			city: "Aurora",
			region: "Colorado",
			postal: "7039 BN",
			country: "Latvia",
			latlong: "-40.31897, -91.89931",
		},
		{
			id: 22,
			firstName: "Tad",
			lastName: "Ellis",
			companyName: "Lacinia Sed Congue Incorporated",
			phone: "1-107-122-1058",
			email: "Sed.et.libero@diamluctus.co.uk",
			address: "9509 Vitae Av.",
			city: "Minucciano",
			region: "Toscana",
			postal: "5199",
			country: "Guatemala",
			latlong: "73.49902, -173.37591",
		},
		{
			id: 23,
			firstName: "Athena",
			lastName: "Mendez",
			companyName: "Eros Proin Ultrices LLP",
			phone: "1-651-557-1187",
			email: "montes.nascetur@nec.org",
			address: "351-5755 Molestie Rd.",
			city: "Lithgow",
			region: "New South Wales",
			postal: "31144",
			country: "Haiti",
			latlong: "37.22916, 80.99339",
		},
		{
			id: 24,
			firstName: "Zelenia",
			lastName: "Carson",
			companyName: "Egestas Foundation",
			phone: "432-2981",
			email: "tortor.at.risus@Nullam.com",
			address: "Ap #212-4007 Amet Rd.",
			city: "San Rafael",
			region: "A",
			postal: "52452",
			country: "Nicaragua",
			latlong: "-7.51949, 159.71235",
		},
		{
			id: 25,
			firstName: "Cain",
			lastName: "Powell",
			companyName: "Praesent Interdum Ligula Industries",
			phone: "168-8333",
			email: "et@Curae.co.uk",
			address: "P.O. Box 227, 5277 Magnis Av.",
			city: "Goiânia",
			region: "Goiás",
			postal: "L05 7NL",
			country: "South Africa",
			latlong: "-60.17634, -117.12668",
		},
		{
			id: 26,
			firstName: "Malik",
			lastName: "Lucas",
			companyName: "Ac PC",
			phone: "1-538-536-0329",
			email: "libero.est.congue@id.ca",
			address: "Ap #744-6562 Et, Road",
			city: "Istanbul",
			region: "Istanbul",
			postal: "8559",
			country: "Liechtenstein",
			latlong: "-48.66892, 165.42832",
		},
		{
			id: 27,
			firstName: "Nevada",
			lastName: "Erickson",
			companyName: "Lobortis Mauris Suspendisse Company",
			phone: "857-7978",
			email: "eget@porttitorvulputateposuere.com",
			address: "P.O. Box 465, 310 Justo Av.",
			city: "Kawerau",
			region: "NI",
			postal: "952085",
			country: "Jamaica",
			latlong: "11.52757, -78.58355",
		},
		{
			id: 28,
			firstName: "Drake",
			lastName: "Williams",
			companyName: "Nec Quam Foundation",
			phone: "703-6516",
			email: "elementum.purus.accumsan@neccursusa.org",
			address: "508-4765 Dapibus Avenue",
			city: "San Joaquín",
			region: "Metropolitana de Santiago",
			postal: "55125",
			country: "Bangladesh",
			latlong: "28.21206, -65.573",
		},
		{
			id: 29,
			firstName: "Dolan",
			lastName: "Lyons",
			companyName: "Et Foundation",
			phone: "660-3254",
			email: "Quisque.ac.libero@non.edu",
			address: "7533 Urna Rd.",
			city: "Springdale",
			region: "Arkansas",
			postal: "257939",
			country: "French Polynesia",
			latlong: "-47.63558, -63.07712",
		},
		{
			id: 30,
			firstName: "Madison",
			lastName: "Rush",
			companyName: "Eu Neque Corp.",
			phone: "878-4482",
			email: "facilisis.vitae@tempusmauriserat.edu",
			address: "P.O. Box 941, 5546 A, Av.",
			city: "La Matap�dia",
			region: "QC",
			postal: "21800",
			country: "Isle of Man",
			latlong: "5.64687, -171.49148",
		},
		{
			id: 31,
			firstName: "Paul",
			lastName: "Mccullough",
			companyName: "Vel Sapien Incorporated",
			phone: "1-979-507-3992",
			email: "Curabitur.egestas.nunc@semsemper.net",
			address: "Ap #178-4382 Vitae Avenue",
			city: "Okpoko",
			region: "Anambra",
			postal: "2911",
			country: "Sudan",
			latlong: "-9.06427, 40.69171",
		},
		{
			id: 32,
			firstName: "Declan",
			lastName: "Spencer",
			companyName: "Luctus Aliquet Odio Ltd",
			phone: "730-0218",
			email: "ornare.lectus.ante@interdumSed.org",
			address: "5123 Nam Av.",
			city: "Bairnsdale",
			region: "VIC",
			postal: "10315",
			country: "Mongolia",
			latlong: "79.03585, 62.3812",
		},
		{
			id: 33,
			firstName: "Gemma",
			lastName: "Nash",
			companyName: "Mus Limited",
			phone: "1-917-882-0764",
			email: "Sed@aliquetodioEtiam.net",
			address: "9989 Dapibus Rd.",
			city: "Woodlands County",
			region: "Alberta",
			postal: "8505",
			country: "Netherlands",
			latlong: "-65.07627, 120.51849",
		},
		{
			id: 34,
			firstName: "Shelley",
			lastName: "Wolf",
			companyName: "Cursus Company",
			phone: "791-0382",
			email: "ante@pedeSuspendissedui.com",
			address: "885-4467 Ac Rd.",
			city: "Abbeville",
			region: "Picardie",
			postal: "374426",
			country: "Åland Islands",
			latlong: "-30.26897, -172.43207",
		},
		{
			id: 35,
			firstName: "Kaitlin",
			lastName: "Moreno",
			companyName: "Vehicula Et Rutrum Associates",
			phone: "1-102-192-3426",
			email: "ullamcorper.viverra@et.com",
			address: "9224 Erat Av.",
			city: "Hertsberge",
			region: "WV",
			postal: "700220",
			country: "Morocco",
			latlong: "14.8958, 56.26835",
		},
		{
			id: 36,
			firstName: "Piper",
			lastName: "Gibbs",
			companyName: "Maecenas Ornare Egestas LLP",
			phone: "366-2536",
			email: "aliquet.Proin.velit@velitCraslorem.ca",
			address: "P.O. Box 602, 9878 Quisque Rd.",
			city: "Kanchrapara",
			region: "West Bengal",
			postal: "68935",
			country: "Saint Helena, Ascension and Tristan da Cunha",
			latlong: "-69.47768, -137.60118",
		},
		{
			id: 37,
			firstName: "Madeline",
			lastName: "Miles",
			companyName: "Sed Dictum Proin Consulting",
			phone: "415-2855",
			email: "tempor.diam.dictum@ipsum.edu",
			address: "5126 Magna Street",
			city: "Vienna",
			region: "Wie",
			postal: "47549",
			country: "Iran",
			latlong: "-29.32235, 57.7887",
		},
		{
			id: 38,
			firstName: "Ursula",
			lastName: "Collins",
			companyName: "Etiam LLC",
			phone: "373-5705",
			email: "nulla.magna@neque.ca",
			address: "739-3307 Dolor, St.",
			city: "Perquenco",
			region: "IX",
			postal: "77862",
			country: "Canada",
			latlong: "17.53695, -155.3334",
		},
		{
			id: 39,
			firstName: "Lydia",
			lastName: "Mooney",
			companyName: "Nibh Associates",
			phone: "916-9232",
			email: "scelerisque.dui.Suspendisse@et.com",
			address: "P.O. Box 466, 8034 Eget, Rd.",
			city: "Cuenca",
			region: "CM",
			postal: "38834",
			country: "France",
			latlong: "17.22048, -28.31764",
		},
		{
			id: 40,
			firstName: "Erica",
			lastName: "Gilbert",
			companyName: "Et Netus Foundation",
			phone: "389-1716",
			email: "lectus.Cum.sociis@tellusNunclectus.com",
			address: "161-7800 Donec Street",
			city: "Recanati",
			region: "Marche",
			postal: "02-639",
			country: "Hong Kong",
			latlong: "82.41502, 0.72436",
		},
		{
			id: 41,
			firstName: "Colin",
			lastName: "Sosa",
			companyName: "Est Mollis Industries",
			phone: "1-984-137-9736",
			email: "at@luctus.net",
			address: "722-5764 Orci St.",
			city: "Lidköping",
			region: "Västra Götalands län",
			postal: "89583",
			country: "Dominican Republic",
			latlong: "7.21644, 23.61365",
		},
		{
			id: 42,
			firstName: "Ronan",
			lastName: "Ortega",
			companyName: "A Magna Lorem Associates",
			phone: "1-716-666-7634",
			email: "aptent.taciti@eteros.net",
			address: "Ap #611-9674 Facilisis Rd.",
			city: "Tranås",
			region: "F",
			postal: "861883",
			country: "Zimbabwe",
			latlong: "-16.23089, -125.91167",
		},
		{
			id: 43,
			firstName: "Chaim",
			lastName: "Lowery",
			companyName: "Libero Consulting",
			phone: "1-552-651-9739",
			email: "posuere@cursusetmagna.com",
			address: "Ap #940-5067 Placerat Road",
			city: "San José de Alajuela",
			region: "A",
			postal: "9477 HT",
			country: "Cambodia",
			latlong: "-32.87537, -24.30377",
		},
		{
			id: 44,
			firstName: "Hu",
			lastName: "Sandoval",
			companyName: "Montes Incorporated",
			phone: "1-922-987-8117",
			email: "libero.lacus@hendrerit.ca",
			address: "9707 Consectetuer St.",
			city: "Niterói",
			region: "RJ",
			postal: "28300-192",
			country: "Korea, North",
			latlong: "-86.38357, 154.53231",
		},
		{
			id: 45,
			firstName: "Garrett",
			lastName: "Ashley",
			companyName: "Est Mauris Ltd",
			phone: "1-241-560-2048",
			email: "elit.sed@Integereu.edu",
			address: "P.O. Box 233, 3054 Nullam Ave",
			city: "Częstochowa",
			region: "SL",
			postal: "7808",
			country: "Saint Helena, Ascension and Tristan da Cunha",
			latlong: "-39.94487, 179.35835",
		},
		{
			id: 46,
			firstName: "Charles",
			lastName: "Guy",
			companyName: "Egestas Blandit Associates",
			phone: "416-3731",
			email: "eget@aliquet.net",
			address: "9240 Ac Road",
			city: "Lidingo",
			region: "AB",
			postal: "04-502",
			country: "Northern Mariana Islands",
			latlong: "-51.01321, 120.6586",
		},
		{
			id: 47,
			firstName: "Haviva",
			lastName: "Coleman",
			companyName: "Odio Corporation",
			phone: "161-9695",
			email: "nonummy.ac.feugiat@nasceturridiculus.co.uk",
			address: "3924 Posuere, Rd.",
			city: "Płock",
			region: "Mazowieckie",
			postal: "2882",
			country: "United States Minor Outlying Islands",
			latlong: "-2.21793, -129.94668",
		},
		{
			id: 48,
			firstName: "Evelyn",
			lastName: "Henry",
			companyName: "A Tortor Nunc Corporation",
			phone: "1-335-282-9511",
			email: "a.arcu.Sed@elementumlorem.edu",
			address: "Ap #600-7984 Tincidunt Ave",
			city: "Gorzów Wielkopolski",
			region: "Lubuskie",
			postal: "73-574",
			country: "Liberia",
			latlong: "-44.42548, 175.57871",
		},
		{
			id: 49,
			firstName: "Joan",
			lastName: "Lopez",
			companyName: "Commodo Ltd",
			phone: "201-7077",
			email: "faucibus.leo.in@sedtortor.co.uk",
			address: "932-877 Ornare. Avenue",
			city: "Grumo Appula",
			region: "PUG",
			postal: "5423",
			country: "Montenegro",
			latlong: "-61.97694, 80.41918",
		},
		{
			id: 50,
			firstName: "Ignatius",
			lastName: "Sexton",
			companyName: "Varius Corp.",
			phone: "633-1411",
			email: "Nulla@urnaetarcu.com",
			address: "4474 Etiam St.",
			city: "Wokingham",
			region: "BR",
			postal: "24747",
			country: "Armenia",
			latlong: "66.55528, -132.22207",
		},
		{
			id: 51,
			firstName: "Cathleen",
			lastName: "Mays",
			companyName: "Vitae Sodales Ltd",
			phone: "428-7008",
			email: "sit@rutrumFuscedolor.edu",
			address: "703-2698 Cras St.",
			city: "Boo",
			region: "AB",
			postal: "1612",
			country: "Belize",
			latlong: "45.1131, 133.01119",
		},
		{
			id: 52,
			firstName: "Troy",
			lastName: "Robertson",
			companyName: "Et Inc.",
			phone: "451-1455",
			email: "in.faucibus.orci@at.com",
			address: "P.O. Box 607, 5711 Fusce Street",
			city: "Kisi",
			region: "OY",
			postal: "9801",
			country: "Kuwait",
			latlong: "86.56396, 145.02232",
		},
		{
			id: 53,
			firstName: "Julian",
			lastName: "Greer",
			companyName: "Risus At PC",
			phone: "732-2513",
			email: "ullamcorper.Duis@atauctor.com",
			address: "673-7124 Id St.",
			city: "Kano",
			region: "KN",
			postal: "37420",
			country: "Congo, the Democratic Republic of the",
			latlong: "62.13967, -47.40381",
		},
		{
			id: 54,
			firstName: "Veda",
			lastName: "Shaffer",
			companyName: "Dignissim Foundation",
			phone: "1-858-903-3424",
			email: "ipsum.dolor.sit@lorem.ca",
			address: "Ap #557-287 Morbi St.",
			city: "Eschwege",
			region: "Hesse",
			postal: "88-803",
			country: "Liberia",
			latlong: "22.62467, 85.94015",
		},
		{
			id: 55,
			firstName: "Yvette",
			lastName: "Gilliam",
			companyName: "Auctor Inc.",
			phone: "1-443-340-3673",
			email: "est@cursuspurus.edu",
			address: "P.O. Box 126, 619 Risus. Street",
			city: "Vitacura",
			region: "RM",
			postal: "8623",
			country: "Sint Maarten",
			latlong: "32.54459, -6.62481",
		},
		{
			id: 56,
			firstName: "Isabella",
			lastName: "Chen",
			companyName: "Nec Enim Ltd",
			phone: "1-185-393-5047",
			email: "Mauris@Nuncpulvinararcu.net",
			address: "5205 Id Road",
			city: "Boo",
			region: "Stockholms län",
			postal: "25207",
			country: "Cyprus",
			latlong: "-34.91847, -62.53616",
		},
		{
			id: 57,
			firstName: "Jael",
			lastName: "Acosta",
			companyName: "Odio Auctor Corporation",
			phone: "1-903-311-1676",
			email: "in.dolor.Fusce@sapien.edu",
			address: "5411 Dui, Ave",
			city: "Guelph",
			region: "Ontario",
			postal: "6527",
			country: "Cayman Islands",
			latlong: "-80.2011, 95.33",
		},
		{
			id: 58,
			firstName: "Chelsea",
			lastName: "Leon",
			companyName: "Et Inc.",
			phone: "656-9030",
			email: "eu.elit@temporest.net",
			address: "P.O. Box 991, 134 Amet, Road",
			city: "Bremerhaven",
			region: "HB",
			postal: "16242",
			country: "American Samoa",
			latlong: "19.99075, 40.87843",
		},
		{
			id: 59,
			firstName: "Uta",
			lastName: "Crosby",
			companyName: "Fringilla Porttitor Corp.",
			phone: "1-368-281-7044",
			email: "Fusce.mi.lorem@Curabiturdictum.edu",
			address: "P.O. Box 525, 8505 Eleifend, Avenue",
			city: "Bydgoszcz",
			region: "KP",
			postal: "21230",
			country: "Pitcairn Islands",
			latlong: "4.15055, 8.03743",
		},
		{
			id: 60,
			firstName: "Velma",
			lastName: "Campbell",
			companyName: "Nunc Ac Institute",
			phone: "1-761-910-9065",
			email: "Donec.at.arcu@lobortis.co.uk",
			address: "Ap #482-5223 Mollis Avenue",
			city: "Los Álamos",
			region: "Biobío",
			postal: "2188 HY",
			country: "Saint Lucia",
			latlong: "-34.65639, -27.26901",
		},
		{
			id: 61,
			firstName: "Asher",
			lastName: "Estrada",
			companyName: "Erat Volutpat Limited",
			phone: "1-246-348-6492",
			email: "auctor@Craseget.ca",
			address: "P.O. Box 519, 4167 Lacus. Rd.",
			city: "Coihueco",
			region: "VII",
			postal: "94-259",
			country: "Pitcairn Islands",
			latlong: "-84.06202, -138.64229",
		},
		{
			id: 62,
			firstName: "Samson",
			lastName: "Hawkins",
			companyName: "Felis Consulting",
			phone: "991-5421",
			email: "tincidunt.orci@placeratvelitQuisque.edu",
			address: "P.O. Box 594, 4266 Purus Rd.",
			city: "Thisnes",
			region: "Luik",
			postal: "1093",
			country: "Tanzania",
			latlong: "-15.01883, -21.52673",
		},
		{
			id: 63,
			firstName: "Oren",
			lastName: "Marquez",
			companyName: "At Velit LLC",
			phone: "660-1141",
			email: "eu.odio.tristique@non.org",
			address: "P.O. Box 908, 4922 Eu Street",
			city: "Brest",
			region: "BR",
			postal: "8362",
			country: "Tuvalu",
			latlong: "78.38888, 62.37906",
		},
		{
			id: 64,
			firstName: "Flynn",
			lastName: "Cox",
			companyName: "Cursus Limited",
			phone: "367-1498",
			email: "scelerisque.dui@Etiam.co.uk",
			address: "210-5349 Volutpat. Ave",
			city: "Etawah",
			region: "Uttar Pradesh",
			postal: "RU09 0WF",
			country: "Myanmar",
			latlong: "42.89719, -71.25152",
		},
		{
			id: 65,
			firstName: "Farrah",
			lastName: "Padilla",
			companyName: "Eros Nam Consulting",
			phone: "1-813-565-8958",
			email: "In.ornare@NullafacilisiSed.net",
			address: "343-3594 Cras Avenue",
			city: "Périgueux",
			region: "Aquitaine",
			postal: "41501",
			country: "Niue",
			latlong: "-17.81897, -178.90247",
		},
		{
			id: 66,
			firstName: "Amal",
			lastName: "Ortega",
			companyName: "Mauris Vel Inc.",
			phone: "1-206-819-1318",
			email: "per@maurissagittisplacerat.com",
			address: "Ap #254-7681 Ornare, Street",
			city: "Delta",
			region: "British Columbia",
			postal: "JG44 6KK",
			country: "Rwanda",
			latlong: "-51.98458, 66.4097",
		},
		{
			id: 67,
			firstName: "Ina",
			lastName: "Britt",
			companyName: "Aliquam Nec Industries",
			phone: "1-769-465-1256",
			email: "amet@luctuslobortisClass.ca",
			address: "1756 Imperdiet Rd.",
			city: "Bellary",
			region: "Karnataka",
			postal: "7433 NC",
			country: "Bouvet Island",
			latlong: "22.2901, -138.06172",
		},
		{
			id: 68,
			firstName: "Ebony",
			lastName: "Payne",
			companyName: "Ridiculus Mus Proin Incorporated",
			phone: "1-299-369-6636",
			email: "Nunc@orci.net",
			address: "P.O. Box 737, 2427 Nulla Rd.",
			city: "Jaén",
			region: "AN",
			postal: "1027 NM",
			country: "Turkey",
			latlong: "-19.19957, 35.34038",
		},
		{
			id: 69,
			firstName: "Phillip",
			lastName: "Walton",
			companyName: "Eu LLC",
			phone: "1-362-664-2345",
			email: "leo.in@duinecurna.ca",
			address: "4729 Rhoncus. Road",
			city: "Oberhausen",
			region: "North Rhine-Westphalia",
			postal: "41603",
			country: "Algeria",
			latlong: "64.05008, -9.30022",
		},
		{
			id: 70,
			firstName: "Idola",
			lastName: "Cummings",
			companyName: "Nonummy Ac Feugiat LLC",
			phone: "909-2751",
			email: "mollis@atauctorullamcorper.co.uk",
			address: "Ap #260-3761 Nisl Av.",
			city: "Pamplona",
			region: "Navarra",
			postal: "2181",
			country: "Anguilla",
			latlong: "-13.66888, 170.63044",
		},
		{
			id: 71,
			firstName: "Iona",
			lastName: "Cummings",
			companyName: "Adipiscing Mauris Corporation",
			phone: "383-6797",
			email: "eu@maurisid.com",
			address: "Ap #911-2955 Ut St.",
			city: "Gölcük",
			region: "Koc",
			postal: "6236",
			country: "Myanmar",
			latlong: "-24.33335, 22.42451",
		},
		{
			id: 72,
			firstName: "Kaitlin",
			lastName: "Johnson",
			companyName: "Mauris Blandit Mattis Incorporated",
			phone: "553-5198",
			email: "eu.tellus.Phasellus@ut.com",
			address: "243-5814 Vel, Rd.",
			city: "Valéncia",
			region: "Comunitat Valenciana",
			postal: "316840",
			country: "Uzbekistan",
			latlong: "38.93955, 146.46779",
		},
		{
			id: 73,
			firstName: "Rudyard",
			lastName: "Franks",
			companyName: "Mauris Inc.",
			phone: "1-538-204-7089",
			email: "vel.pede.blandit@sem.org",
			address: "P.O. Box 409, 3933 Luctus Avenue",
			city: "Berlin",
			region: "Berlin",
			postal: "P2G 4J3",
			country: "Macao",
			latlong: "10.0186, -111.08044",
		},
		{
			id: 74,
			firstName: "Devin",
			lastName: "Snow",
			companyName: "Vel Est PC",
			phone: "268-9068",
			email: "Donec.luctus@estacfacilisis.co.uk",
			address: "P.O. Box 576, 6915 Ipsum Road",
			city: "Jacksonville",
			region: "Florida",
			postal: "26931-660",
			country: "Chile",
			latlong: "-68.60298, 90.55506",
		},
		{
			id: 75,
			firstName: "Karly",
			lastName: "May",
			companyName: "Placerat Augue Sed Consulting",
			phone: "278-0091",
			email: "ac@disparturient.co.uk",
			address: "3438 Lacus. Av.",
			city: "Watson Lake",
			region: "YK",
			postal: "66531",
			country: "Comoros",
			latlong: "53.73788, -97.37417",
		},
		{
			id: 76,
			firstName: "Lydia",
			lastName: "Tucker",
			companyName: "Enim Sit Amet Foundation",
			phone: "456-8672",
			email: "tincidunt.Donec@commodoipsum.ca",
			address: "P.O. Box 305, 1568 Curabitur Road",
			city: "Girona",
			region: "CA",
			postal: "646871",
			country: "Guatemala",
			latlong: "30.1492, -137.63979",
		},
		{
			id: 77,
			firstName: "Adrienne",
			lastName: "Brennan",
			companyName: "Vivamus Industries",
			phone: "963-6589",
			email: "dui@NullamenimSed.ca",
			address: "P.O. Box 497, 8544 Nunc Rd.",
			city: "Galway",
			region: "C",
			postal: "05492",
			country: "Russian Federation",
			latlong: "-62.61059, -169.91162",
		},
		{
			id: 78,
			firstName: "Moses",
			lastName: "Meyer",
			companyName: "Tellus Suspendisse Consulting",
			phone: "241-4577",
			email: "nunc@mattis.co.uk",
			address: "P.O. Box 210, 7543 Nulla St.",
			city: "Santa Luzia",
			region: "Minas Gerais",
			postal: "70092",
			country: "Cuba",
			latlong: "86.69886, -80.07049",
		},
		{
			id: 79,
			firstName: "Malachi",
			lastName: "Whitney",
			companyName: "Semper Foundation",
			phone: "1-220-633-0209",
			email: "consequat.nec.mollis@risusDuis.edu",
			address: "P.O. Box 525, 9613 Fusce Avenue",
			city: "Ipswich",
			region: "Queensland",
			postal: "SA8 6AG",
			country: "Sudan",
			latlong: "-76.34709, -43.59039",
		},
		{
			id: 80,
			firstName: "Georgia",
			lastName: "Dotson",
			companyName: "Hendrerit Neque In Foundation",
			phone: "534-3389",
			email: "arcu.Sed@consequat.com",
			address: "Ap #580-2908 Dolor Ave",
			city: "Montese",
			region: "Emilia-Romagna",
			postal: "G9R 2J6",
			country: "Belarus",
			latlong: "14.12896, 81.22962",
		},
		{
			id: 81,
			firstName: "Jamalia",
			lastName: "Livingston",
			companyName: "Justo Proin Non Incorporated",
			phone: "1-590-578-5721",
			email: "nec.imperdiet.nec@risusquis.net",
			address: "629-2928 Feugiat. Rd.",
			city: "Sirsa",
			region: "HR",
			postal: "69633",
			country: "Romania",
			latlong: "22.45729, -51.38539",
		},
		{
			id: 82,
			firstName: "Kendall",
			lastName: "Odom",
			companyName: "Nec Malesuada Ut Company",
			phone: "659-6462",
			email: "laoreet.ipsum@Aeneangravida.org",
			address: "1152 Urna St.",
			city: "Berlin",
			region: "BE",
			postal: "5352 BO",
			country: "India",
			latlong: "53.10565, -42.44083",
		},
		{
			id: 83,
			firstName: "Melinda",
			lastName: "Ray",
			companyName: "Ligula Consulting",
			phone: "1-676-711-3984",
			email: "rhoncus@blanditenimconsequat.ca",
			address: "Ap #749-6032 Nec Rd.",
			city: "Buguma",
			region: "RI",
			postal: "7211",
			country: "Andorra",
			latlong: "-66.47937, -19.32697",
		},
		{
			id: 84,
			firstName: "Candice",
			lastName: "Mcgowan",
			companyName: "Magnis Foundation",
			phone: "1-539-344-5841",
			email: "lectus.justo.eu@Morbi.com",
			address: "411-4228 Purus, Rd.",
			city: "Kerikeri",
			region: "North Island",
			postal: "RE2 5GC",
			country: "Niger",
			latlong: "18.17267, 4.38161",
		},
		{
			id: 85,
			firstName: "Cynthia",
			lastName: "Goff",
			companyName: "Dolor Quam LLP",
			phone: "801-1268",
			email: "tempor@vulputaterisus.org",
			address: "630-8410 Nec Road",
			city: "Baton Rouge",
			region: "LA",
			postal: "26440-786",
			country: "Benin",
			latlong: "-72.48588, -50.57804",
		},
		{
			id: 86,
			firstName: "Lacy",
			lastName: "Cook",
			companyName: "Donec Egestas Incorporated",
			phone: "1-200-497-0955",
			email: "fermentum.risus@eros.org",
			address: "Ap #104-8815 Id Av.",
			city: "Delta",
			region: "BC",
			postal: "04-518",
			country: "Greenland",
			latlong: "-56.47198, -81.31912",
		},
		{
			id: 87,
			firstName: "Hashim",
			lastName: "Becker",
			companyName: "Sed Congue Limited",
			phone: "1-738-393-2086",
			email: "non@adipiscinglobortis.org",
			address: "Ap #904-865 Mollis St.",
			city: "Curitiba",
			region: "Paraná",
			postal: "9692",
			country: "Colombia",
			latlong: "-18.30192, -58.28911",
		},
		{
			id: 88,
			firstName: "Mallory",
			lastName: "Mcdonald",
			companyName: "Rhoncus Donec Est PC",
			phone: "357-5959",
			email: "erat@nonmagna.org",
			address: "4977 Arcu Road",
			city: "Istanbul",
			region: "Ist",
			postal: "PP9 5DG",
			country: "Faroe Islands",
			latlong: "70.61728, -101.91301",
		},
		{
			id: 89,
			firstName: "Avye",
			lastName: "Mccarthy",
			companyName: "Augue Consulting",
			phone: "739-5366",
			email: "malesuada@lacus.com",
			address: "446-3245 Tincidunt Avenue",
			city: "Stalowa Wola",
			region: "PK",
			postal: "94818",
			country: "Jersey",
			latlong: "72.53092, 148.30005",
		},
		{
			id: 90,
			firstName: "Imelda",
			lastName: "Salas",
			companyName: "Felis Adipiscing Corp.",
			phone: "231-3217",
			email: "lectus.Nullam@Maecenasiaculis.net",
			address: "P.O. Box 376, 9461 Felis. Av.",
			city: "Istanbul",
			region: "Istanbul",
			postal: "4804",
			country: "Italy",
			latlong: "-8.13604, 65.57862",
		},
		{
			id: 91,
			firstName: "George",
			lastName: "Logan",
			companyName: "Aliquet Industries",
			phone: "224-2123",
			email: "eu.tellus.Phasellus@tellus.ca",
			address: "665-7226 Mi St.",
			city: "Rzeszów",
			region: "PK",
			postal: "85-392",
			country: "Bermuda",
			latlong: "38.3492, 94.32292",
		},
		{
			id: 92,
			firstName: "Grady",
			lastName: "Hurst",
			companyName: "Non Foundation",
			phone: "800-4640",
			email: "congue.turpis.In@Fusce.net",
			address: "3796 Egestas. St.",
			city: "De Haan",
			region: "West-Vlaanderen",
			postal: "70073",
			country: "Poland",
			latlong: "77.38737, -137.07566",
		},
		{
			id: 93,
			firstName: "Yael",
			lastName: "Decker",
			companyName: "Egestas Urna Institute",
			phone: "411-4794",
			email: "quis@nec.edu",
			address: "Ap #905-2509 Facilisis, Road",
			city: "Cambridge",
			region: "North Island",
			postal: "34078",
			country: "Greece",
			latlong: "28.17608, 27.46397",
		},
		{
			id: 94,
			firstName: "Vincent",
			lastName: "Decker",
			companyName: "Dis Parturient PC",
			phone: "1-554-414-2305",
			email: "Phasellus.vitae@pedeSuspendissedui.net",
			address: "Ap #390-3545 Euismod St.",
			city: "Makurdi",
			region: "BE",
			postal: "102442",
			country: "Liechtenstein",
			latlong: "-66.08526, 151.03772",
		},
		{
			id: 95,
			firstName: "Winter",
			lastName: "Russo",
			companyName: "Parturient Montes Corporation",
			phone: "1-165-112-7031",
			email: "Mauris@malesuadautsem.net",
			address: "4105 Sapien Rd.",
			city: "Lagos",
			region: "Lagos",
			postal: "98-831",
			country: "Afghanistan",
			latlong: "78.91735, -38.20191",
		},
		{
			id: 96,
			firstName: "Amethyst",
			lastName: "Hurst",
			companyName: "Aliquam Gravida Company",
			phone: "1-726-984-3750",
			email: "ullamcorper@scelerisquescelerisquedui.ca",
			address: "875-6604 Vel, Street",
			city: "Ipswich",
			region: "SF",
			postal: "88170",
			country: "French Polynesia",
			latlong: "-7.98555, 138.06646",
		},
		{
			id: 97,
			firstName: "Libby",
			lastName: "Sherman",
			companyName: "Euismod Urna Incorporated",
			phone: "988-2118",
			email: "pede.Nunc.sed@vitae.net",
			address: "P.O. Box 101, 7274 Nibh Street",
			city: "Wolkrange",
			region: "Luxemburg",
			postal: "18737",
			country: "France",
			latlong: "-32.02191, 102.3188",
		},
		{
			id: 98,
			firstName: "Akeem",
			lastName: "Rivers",
			companyName: "Purus Institute",
			phone: "330-9191",
			email: "mollis@cursusNuncmauris.ca",
			address: "6432 Non, St.",
			city: "Nicoya",
			region: "G",
			postal: "97222-934",
			country: "Bosnia and Herzegovina",
			latlong: "-77.75986, 179.39302",
		},
		{
			id: 99,
			firstName: "Joseph",
			lastName: "Powers",
			companyName: "Egestas Aliquam Nec Institute",
			phone: "1-547-248-7927",
			email: "Proin.nisl@ametlorem.co.uk",
			address: "747-629 Vulputate Avenue",
			city: "Gouda",
			region: "Zuid Holland",
			postal: "11798",
			country: "Syria",
			latlong: "-58.87714, -123.24194",
		},
		{
			id: 100,
			firstName: "Sade",
			lastName: "Foley",
			companyName: "Phasellus Company",
			phone: "1-638-747-8408",
			email: "pellentesque.tellus.sem@penatibuset.edu",
			address: "Ap #663-2135 Mollis. Av.",
			city: "Kuşadası",
			region: "Aydın",
			postal: "7039",
			country: "Zambia",
			latlong: "-6.31082, 3.55689",
		},
	],
})

const items = computed(() => state.allItems.slice(0, state.maxRows))
const useColumns = computed(() => state.columns.slice(0, state.maxColumns))
</script>
<style>
table.scrolling .w2 {
	width: 20em;
	min-width: 20em;
	max-width: 20em;
}

table.scrolling tfoot tr th {
	width: 130em;
	min-width: 130em;
	max-width: 130em;
}

table.freezeFirstColumn thead tr,
table.freezeFirstColumn tbody tr {
	display: block;
	width: min-content;
}

table.freezeFirstColumn thead td:first-child,
table.freezeFirstColumn tbody td:first-child,
table.freezeFirstColumn thead th:first-child,
table.freezeFirstColumn tbody th:first-child {
	position: sticky;
	position: -webkit-sticky;
	left: 0;
}

* {
	font-family: sans-serif;
}

.box {
	clear: both;
	padding: 0;
	min-height: 300px;
	height: 40vh;
	margin-left: auto;
	margin-right: auto;
	overflow: hidden;
}
</style>
